### ISSUE TITLE
Phx 1.7-dev:  Phoenix.Router.Route.exprs/1 is undefined or private

### ISSUE THREAD

**Issue by rubas** [elixir-cldr/cldr_routes#10]
[    routes_with_exprs = Enum.map(routes, &{&1, Phoenix.Router.Route.exprs(&1)})](https://github.com/elixir-cldr/cldr_routes/blob/e527ae5a8ef80c9119e8ab72d79ee009ce1d0669/lib/cldr/route.ex#L288)

This line changed in Phoenix.

https://github.com/phoenixframework/phoenix/blob/b3592c38a93bbb61dbf29d1c11245f350500797c/lib/phoenix/router.ex#L493

**Comment by BartOtten** [comment]
This should be helpful (consider aliasing Phoenix.Router.Route). Using `apply` silences the warning.
  
```
def exprs(route, env) do
    if Kernel.function_exported?(Phoenix.Router.Route, :exprs, 2) do
      forwards = env.module |> Module.get_attribute(:phoenix_forwards)
      apply(Phoenix.Router.Route, :exprs, [route, forwards])
    else
      apply(Phoenix.Router.Route, :exprs, [route])
    end
  end
```

**Comment by kipcole9** [comment]
@BartOtten thanks very much. I know I am way behind in getting this lib up-to-date. This will definitely help.

**Comment by kipcole9** [comment]
Ah, turns out I'd already made that change.  I've done all the hard work on verified routes too - except the actual path translation which I just haven't prioritised. I will get this finished up in the next few days.

**Comment by ry-TU** [comment]
@kipcole9 first of all thanks for your hard work generally for `cldr`, given Phoenix 1.7 is already out is there any chance we can publish a release to get the fix? Is there anything missing or we can help with to get this released?
